server:
  port: 8080

spring:
  kafka:
    # Note: the first time publishing the message, it may show "no lead broker"? But it will be fine the next times
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer


